#include <menu.h>

#define PCONST(ty, NAME) printf("pub const " #NAME ": " #ty " = %d;\n", NAME)

int main() {
	PCONST(i32, O_ONEVALUE);
	PCONST(i32, O_SHOWDESC);
	PCONST(i32, O_ROWMAJOR);
	PCONST(i32, O_IGNORECASE);
	PCONST(i32, O_SHOWMATCH);
	PCONST(i32, O_NONCYCLIC);
	PCONST(i32, O_SELECTABLE);

	PCONST(i32, REQ_LEFT_ITEM);
	PCONST(i32, REQ_RIGHT_ITEM);
	PCONST(i32, REQ_UP_ITEM);
	PCONST(i32, REQ_DOWN_ITEM);
	PCONST(i32, REQ_SCR_ULINE);
	PCONST(i32, REQ_SCR_DLINE);
	PCONST(i32, REQ_SCR_DPAGE);
	PCONST(i32, REQ_SCR_UPAGE);
	PCONST(i32, REQ_FIRST_ITEM);
	PCONST(i32, REQ_LAST_ITEM);
	PCONST(i32, REQ_NEXT_ITEM);
	PCONST(i32, REQ_PREV_ITEM);
	PCONST(i32, REQ_TOGGLE_ITEM);

	PCONST(i32, REQ_CLEAR_PATTERN);
	PCONST(i32, REQ_BACK_PATTERN);
	PCONST(i32, REQ_NEXT_MATCH);
	PCONST(i32, REQ_PREV_MATCH);

#ifdef MIN_MENU_COMMAND
	PCONST(i32, MIN_MENU_COMMAND);
#endif

#ifdef MAX_MENU_COMMAND
	PCONST(i32, MAX_MENU_COMMAND);
#endif
}
